# Generated by Django 5.2.8 on 2025-12-16 15:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Logement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "type_logement",
                    models.CharField(
                        choices=[
                            ("chambre", "Chambre"),
                            ("studio", "Studio"),
                            ("appartement", "Appartement"),
                            ("villa", "Villa"),
                            ("duplex", "Duplex"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ville", models.CharField(max_length=255)),
                ("quartier", models.CharField(max_length=255)),
                ("superficie", models.PositiveIntegerField(blank=True, null=True)),
                ("nombre_pieces", models.PositiveIntegerField(default=1)),
                ("disponibilite", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("mod", models.ImageField(upload_to="")),
            ],
            options={
                "verbose_name": "Logement",
                "verbose_name_plural": "Logements",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "logement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="listings.logement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
        ),
    ]
