# Generated by Django 5.2.8 on 2025-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_remove_logement_mod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(),
        ),
    ]
