# Generated by Django 5.2.8 on 2025-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="logement",
            name="Paking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logement",
            name="chambres",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="logement",
            name="eau_electricite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logement",
            name="internet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logement",
            name="meuble",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="logement",
            name="salles_bain",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="logement",
            name="quartier",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="logement",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="logement",
            name="ville",
            field=models.CharField(max_length=100),
        ),
    ]
