# Generated by Django 5.2.8 on 2025-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_logement_paking_logement_chambres_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logement",
            name="cuisine",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="logement",
            name="salon",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
