# Generated by Django 5.2.8 on 2025-12-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_logement_cuisine_logement_salon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logement",
            name="chambres",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="logement",
            name="cuisine",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="logement",
            name="salles_bain",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="logement",
            name="salon",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
