# Generated by Django 5.2.8 on 2025-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_logement_chambres_alter_logement_cuisine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logement",
            name="Paking",
        ),
        migrations.AddField(
            model_name="logement",
            name="parking",
            field=models.BooleanField(default=False, verbose_name="Parking"),
        ),
        migrations.AlterField(
            model_name="logement",
            name="eau_electricite",
            field=models.BooleanField(default=False, verbose_name="Eau et électricité"),
        ),
    ]
