# Generated by Django 5.2.8 on 2025-12-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_remove_logement_paking_logement_parking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.CharField(),
        ),
    ]
