# Generated by Django 5.2.8 on 2025-12-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="ordre",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(upload_to="listings/"),
        ),
    ]
