# Generated by Django 5.2.8 on 2025-12-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_alter_image_ordre_alter_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="url",
            new_name="image",
        ),
    ]
